
const data=[
    {
    id:1,
    name:"TajMahal, Agra",
    info:"Agra is a city on the banks of the Yamuna river in the Indian state of Uttar Pradesh, about 230 kilometres south-east of the national capital Delhi and 330 km west of the state capital Lucknow.",
    image:"https://images.asiahighlights.com/allpicture/2020/04/00524275685e47b18d957a05_cut_600x800_315.jpg",
    price:"70.5K",    
    },
    {
    id:2,
    name:"GolKonda Fort, Haidrabad",
    info:"Hyderabad is the capital of southern India's Telangana state. A major center for the technology industry, it's home to many upscale restaurants and shops. Its historic sites include Golconda Fort, a former diamond-trading center that was once the Qutb Shahi dynastic capital.",
    image:"https://content.jdmagicbox.com/comp/hyderabad/88/040p2600288/catalogue/charminar-fort-charminar-hyderabad-tourist-attraction-p9if.jpg?clr=",
    price:"80.99K",
    },
    {
    id:3,
    name:"Red Fort, Delhi",
    info:"Delhi, India’s capital territory, is a massive metropolitan area in the country’s north. In Old Delhi, a neighborhood dating to the 1600s, stands the imposing Mughal-era Red Fort, a symbol of India",
    image:"https://www.india-a2z.com/images/redfort.jpg",
    price:"40.8K",
    },
    {
    id:4,
    name:"Jaipur",
    info:"Jaipur is the capital of India’s Rajasthan state. It evokes the royal family that once ruled the region and that, in 1727, founded what is now called the Old City, or “Pink City” for its trademark building color. At the center of its stately street grid (notable in India) stands the opulent, colonnaded City Palace complex",
    image:"https://upload.wikimedia.org/wikipedia/commons/4/41/East_facade_Hawa_Mahal_Jaipur_from_ground_level_%28July_2022%29_-_img_01.jpg",
    price:"30.2K",
    },
    {
    id:5,
    name:"Mumbai",
    info:"Mumbai is a densely populated city on India’s west coast. A financial center, it's India's largest city. On the Mumbai Harbour waterfront stands the iconic Gateway of India stone arch, built by the British Raj in 1924",
    image:"https://www.india-briefing.com/news/wp-content/uploads/2013/07/India-Briefing-Economy-of-Mumbai-Indias-Major-Commercial-Hub.jpg",
    price:"90.6K",
    },
    {
        id:6,
        name:"Goa",
        info:"Goa is a state in western India with coastlines stretching along the Arabian Sea. Its long history as a Portuguese colony prior to 1961 is evident in its preserved 17th-century churches and the area’s tropical spice plantations.",
        image:"https://media.easemytrip.com/media/Blog/India/637245472281678954/6372454722816789543img5H.png",
        price:"10.4K",
    },
    {
        id:7,
        name:"Amer Fort, Rajasthan",
        info:"Amer Fort or Amber Fort is a fort located in Amer, Rajasthan, India. Amer is a town with an area of 4 square kilometres located 11 kilometres from Jaipur, the capital of Rajasthan. Located high on a hill, it is the principal tourist attraction in Jaipur.",
        image:"https://img.veenaworld.com/wp-content/uploads/2021/07/Amer-Fort-Jaipur-Ticket-Price-History-Timings-Things-to-Do.jpg",
        price:"90.8K",
    },
    {
        id:8,
        name:"Golden Temple, Punjab",
        info:"The Golden Temple is a gurdwara located in the city of Amritsar, Punjab, India. It is the pre-eminent spiritual site of Sikhism. It is one of the holiest sites in Sikhism, alongside the Gurdwara Darbar Sahib Kartarpur in Kartarpur, and Gurdwara Janam Asthan in Nankana Sahib",
        image:"https://upload.wikimedia.org/wikipedia/commons/9/94/The_Golden_Temple_of_Amrithsar_7.jpg",
        price:"20.8K",
    },
    {
        id:9,
        name:"Ganges River's, Varanasi",
        info:"Varanasi is a city in the northern Indian state of Uttar Pradesh dating to the 11th century B.C. Regarded as the spiritual capital of India, the city draws Hindu pilgrims who bathe in the Ganges River’s sacred waters and perform funeral rites",
        image:"https://ychef.files.bbci.co.uk/1280x720/p07cbjg1.jpg",
        price:"16.8K",
    },
    {
        id:10,
        name:"National Park, Uttarakhand",
        info:"Jim Corbett National Park is a forested wildlife sanctuary in northern India’s Uttarakhand State. Rich in flora and fauna, it’s known for its Bengal tigers. Animals, including tigers, leopards and wild elephants, roam the Dhikala zone. On the banks of the Ramganga Reservoir, the Sonanadi zone is home to elephants and leopards, along with hundreds of species of birds.",
        image:"https://m.economictimes.com/thumb/msid-86814136,width-1200,height-900,resizemode-4,imgsize-237348/1.jpg",
        price:"71.1K",
    },
    {
        id:11,
        name:"Jodhpur, Rajasthan",
        info:"Mehrangarh is a historic fort located in Jodhpur, Rajasthan, India. It stands on a hilltop, rising about 122 meters above the surrounding plains. The complex spans 1,200 acres.",
        image:"https://cdn.britannica.com/39/242539-050-97AFAE4E/Mehrangarh-fortress-Jodhpur-Rajasthan-India.jpg",
        price:"21.89K",
    },
    {
        id:12,
        name:"Hawa Mahal, Rajasthan",
        info:"The Hawa Mahal is a palace in the city of Jaipur, Rajasthan, India. Built from red and pink sandstone, it is on the edge of the City Palace, Jaipur, and extends to the Zenana, or women's chambers.",
        image:"https://a.travel-assets.com/findyours-php/viewfinder/images/res70/68000/68291-Hawa-Mahal.jpg",
        price:"22.00K",
    },
    {
        id:13,
        name:"Humayun's tomb, New Delhi",
        info:"Humayun's tomb is the tomb of Mughal emperor, Mirza Nasir al-Din Muhammad commonly known as Humayun situated in Delhi, India.",
        image:"https://tds-images.thedailystar.net/sites/default/files/feature/images/3_19.jpg",
        price:"25.73K",
    },
    {
        id:14,
        name:"Swaminarayan Akshardham, Delhi",
        info:"Swaminarayan Akshardham is a Hindu temple, and spiritual-cultural campus in Delhi, India. The temple is close to the border with Noida. Also referred to as Akshardham Temple or Akshardham Delhi, the complex displays millennia of traditional and modern Hindu culture, spirituality, and architecture.",
        image:"https://akshardham.com/newdelhi/wp-content/uploads/2020/10/AKDM-04-1-Copy.jpg",
        price:"22K",
    },
    {
        id:15,
        name:"Mahabodhi Temple, Bihar",
        info:"The Mahabodhi Temple or the Mahābodhi Mahāvihāra, a UNESCO World Heritage Site, is an ancient, but rebuilt and restored Buddhist temple in Bodh Gaya, Bihar, India, marking the location where the Buddha is said to have attained enlightenment. Bodh Gaya is 15 km from Gaya and is about 96 km from Patna.",
        image:"https://static.toiimg.com/photo/47081465.cms",
        price:"18.99K",
    },
    {
        id:16,
        name:"National Park, Rajasthan",
        info:"Ranthambore National Park is a vast wildlife reserve near the town of Sawai Madhopur in Rajasthan, northern India. It is a former royal hunting ground and home to tigers, leopards and marsh crocodiles.",
        image:"https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2021/10/22161827/Inside-Image-Horizontal-35.jpeg",
        price:"18.34K",
    },
    {
        id:17,
        name:"India Gate, Delhi",
        info:"The India Gate is a war memorial located near the Kartavya path on the eastern edge of the ceremonial axis of New Delhi, formerly called Rajpath.",
        image:"https://img.staticmb.com/mbcontent/images/crop/uploads/2022/9/India%20Gate%20delhi_0_1200.jpg",
        price:"22.00K",
    },
];

export default data;